services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dangarpra/chatbot-frontend:v1.0.1
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dangarpra/chatbot-backend:v1.0.1
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    environment:
      - COHERE_API_KEY=8Ur9ffDfdPJqvxC4yTNx2GItkaHrLWcPImOfssz2
      - PINECONE_API_KEY=pcsk_2Q5SR6_RwRvbb2vr3Yi372tm17eCo9CVSrBbsMgCa7QVwoWhFiPDEvqeDwm8KEdggX8zAd
      - PINECONE_ENVIRONMENT=us-east-1
      - PINECONE_HOST=https://desafiofinal-n7162mc.svc.aped-4627-b74a.pinecone.io
      - INDEX_NAME=desafiofinal
      - BBDD_USERNAME="admin"
      - BBDD_PASSWORD="desafiofinal"
      - BBDD_HOST="desafio.ct8kyq8mytxu.us-east-2.rds.amazonaws.com"
      - BBDD_PORT=3306
    